### ISSUE TITLE
bootstrap.sh script fails at add-apt-repository -y ppa:pi-rho/dev

### ISSUE THREAD

**Issue by Sosthene00** [jnewbery/btc-dev#15]
I succeeded setting up the VM some times ago, but recently it hit the drive max capacity and I destroyed the VM thinking I could just run the script anew to create a new one. But I experienced a lot of issue after that, I couldn't manage to bootstrap another VM that would word to build Bitcoin. 
It seems I nailed it with the `add-apt-repository -y ppa:pi-rho/dev` in the bootstrap script which seems to systematically time out: script is interrupted with a `Error: retrieving gpg key timed out.`.
So I first ssh into my VM and added the ppa key manually from there, it worked. But then connectivity is painful slow, it takes hours to download all that I need.
Any idea why the script would fail?
My conf:
5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Vagrant 2.0.2
Version 5.2.32_Ubuntu r132056

**Comment by jnewbery** [comment]
Is this still failing for you? I managed to run this successfully and the `add-apt-repository` command was successful.
