### ISSUE TITLE
Getting started with contribution to bitcoin need help!!

### ISSUE THREAD

**Issue by Tharun-tharun** [jnewbery/btc-dev#16]
I would like to become a bitcoin core contributor not a developer like the way you said in the medium article, yes I read your medium article that was a good article for beginners like me to get understand a basic level of understanding about it, Can you guide me on how to get started with also I'm learning golang and python on the way what's your suggestion on other programming languages to learn like C++ something like that. I would like to hear from you to get started. Thanks!

**Comment by jnewbery** [comment]
Hi @Tharun-tharun. I suggest you check out Bitcoin Core PR Review Club: https://bitcoincore.reviews/. Every week we review a PR together and there's a meeting to ask questions and discuss. There are also links to other resources on that site.

**Comment by Tharun-tharun** [comment]
Thank you! for your immediate response, I'll have a check them.
